### ISSUE TITLE
Github actions do not allow me to push to branches

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#11]
I cannot make a github action push to a branch In this repository. The option on [this page](https://github.com/NFDI4BIOIMAGE/training/settings/actions) is deactivated:

![image](https://github.com/NFDI4BIOIMAGE/training/assets/12660498/6958cab1-39d4-490f-a78a-dc8d2102efea)

Might it be possible to activate this checkbox if `NFDI4BIOIMAGE` was paying to github?

Do you know by chance @joshmoore ?

**Comment by haesleinhuepf** [comment]
Ok, I figured out [reading here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-select-actions-and-reusable-workflows-to-run). I had to activate the option on [organization level](https://github.com/organizations/NFDI4BIOIMAGE/settings/actions). Let me know if that's bad @joshmoore and thanks for reading :-)

**Comment by joshmoore** [comment]
Probably the only result is that others who are managing repositories might have to be a bit more careful about how they set up their actions, but I didn't see any horrific warnings on the linked doc pages.
