### ISSUE TITLE
Idea: link to page with content organized by date of publication

### ISSUE THREAD

**Issue by zoccoler** [NFDI4BIOIMAGE/training#117]
This material is organized by tag, content type and license.

After the last TA5 meeting, I thought if it would it be useful/hard to have a link to the contents organized by publish date, similar to a blog post, so that users could check "what is new".

**Comment by haesleinhuepf** [comment]
Fantastic idea!

@SeverusYixin could you maybe have a look into this?

**Comment by SeverusYixin** [comment]
Very nice idea, I was thinking about this too, like sorting them by date would be like sorting from new to old, old to new. I will deal with this when the search engine is done. Also thinking about how to add these dates efficiently and legally, if you have any ideas, you can also write them here https://github.com/NFDI4BIOIMAGE/search_engine I will be happy to share them with you.

**Comment by haesleinhuepf** [comment]
Just an idea: This part of the table of contents:

![image](https://github.com/user-attachments/assets/934964de-724b-40f4-8cb9-95dddddb51d4)


Is generated here:

https://github.com/NFDI4BIOIMAGE/training/blob/main/scripts/generate_link_lists.py#L18-L27

Do you think it is possible to do this also for recently added entries?

**Comment by SeverusYixin** [comment]
Hi@haesleinhuepf, I want to make sure I haven't misunderstood: does this also have to be displayed on the website that has already been published?

**Comment by haesleinhuepf** [comment]
That would be fantastic @SeverusYixin ! If you write a python script that generates a list of recently added materials, I will show you how to embed it in the website.
