### ISSUE TITLE
Add "software" tag/content type?

### ISSUE THREAD

**Issue by ClementCaporal** [NFDI4BIOIMAGE/training#13]
Hello,

Would a tag concerning image analysis application **software** be useful? I'm thinking of being able to sort learning resources in python / imageJ for example.

Maybe it's an unnecessary layer of complexity?

Thanks

**Comment by haesleinhuepf** [comment]
Good question. It might be better to add software to biii.eu directly. It is a rich resource already, which we might not want to copy though.

I keep this issue open to keep  the discusion ongoing and see what others think

**Comment by ClementCaporal** [comment]
Thank you for your answer!
I think I misspoke. I didn't mean to make a list of existing software.

What I meant was that in the list of training courses, in addition to theory, there are sometimes examples of software implementations. For example:
- this resource uses only FIJI (https://syn.mrc-lmb.cam.ac.uk/acardona/fiji-tutorial/)
- this resource uses only python (https://github.com/guiwitz/Python_image_processing)
- This resource uses both (https://bioimagebook.github.io/index.html)

Would it be useful to add a filter to have only courses associated with python, for example?

**Comment by haesleinhuepf** [comment]
yes, that makes so much sense! we can use tags for that

```
tags:
- python
```
