### ISSUE TITLE
Determine date of entries

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#135]
For each entry, we should have dates, e.g.:
* Date of publication
* Date of adding the entry to our database

This will help solving #117 
CC @SeverusYixin

**Comment by SeverusYixin** [comment]
"Date of adding the entry to our database" means: the date when people add a new material to our yml file(datasource).

**Comment by SeverusYixin** [comment]
Hi @haesleinhuepf, should we close this issue?  It's also complete.
