### ISSUE TITLE
Gather download statistics weekly

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#144]
It should be possible to run scripts/summary_download_statistics.py on a weekly basis using github workflows as explained here:
https://jasonet.co/posts/scheduled-actions/

We should also modify the script so that it submits a pull-request. We could use these two functions in _github_utilities.py:
* [create_branch](https://github.com/NFDI4BIOIMAGE/training/blob/347d0e2ec04bee0268f5059662bff67ffd6254a7/scripts/_github_utilities.py#L117)
* [write_file](https://github.com/NFDI4BIOIMAGE/training/blob/347d0e2ec04bee0268f5059662bff67ffd6254a7/scripts/_github_utilities.py#L57)
* [send_pull_request](https://github.com/NFDI4BIOIMAGE/training/blob/347d0e2ec04bee0268f5059662bff67ffd6254a7/scripts/_github_utilities.py#L179)

**Comment by haesleinhuepf** [comment]
@marabuuu Would you accept that challenge? (-:
We can also do it together in a mini-hackathon in autumn if you like.

**Comment by marabuuu** [comment]
Sounds good, I am happy to look into it. Until this is merged, are we manually adding the download_statistics.csv monthly?

**Comment by haesleinhuepf** [comment]
Yes, or biweekly. I just did it today. No hurry! :-)
