### ISSUE TITLE
Training material URL does not work

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/training#168]
Hi @haesleinhuepf , 
I just find some date like:
Train-the-Trainer Concept on Research Data Management
Authors: Katarzyna Biernacka, Maik Bierwirth, Petra Buchholz, Dominika Dolzycka, Kerstin Helbig, Janna Neumann, Carolin Odebrecht, Cord Wiljes, Ulrike Wuttke

License: CC-BY-4.0

Type: Book

Tags: Research Data Management

URL: https://zenodo.org/record/4071471,https://doi.org/10.5281/zenodo.4071471

The URL doesn't seem to work.

**Comment by haesleinhuepf** [comment]
It seems a list of two links:
- https://zenodo.org/record/4071471
- https://doi.org/10.5281/zenodo.4071471

**Comment by SeverusYixin** [comment]
> https://doi.org/10.5281/zenodo.4071471

Got it :)

**Comment by SeverusYixin** [comment]
> It seems a list of two links:
> 
> * https://zenodo.org/record/4071471
> * https://doi.org/10.5281/zenodo.4071471

Got it :)

**Comment by haesleinhuepf** [comment]
Hi @SeverusYixin ,

are there any news on this issue?

Thanks!

**Comment by SeverusYixin** [comment]
> Hi @SeverusYixin ,
> 
> are there any news on this issue?
> 
> Thanks!

Yes, it's already displayed, but there are still some details, for example, if there are two URLs, these two URLs are the same page, do we need to delete one of them?

Actually, I wanted to discuss these problems with you last Tuesday.

**Comment by SeverusYixin** [comment]
> We currently have 68 resources ([source](https://github.com/NFDI4BIOIMAGE/training/issues/300)) with multiple URLs. If we removed one of them, sooner or later people might add these urls again as new entries, because the urls are not in the database. We would then have 68 duplicated entries. That's why having multiple URLs is absolutely normal and will not be changed.

Okay, then there is no problem. I will add a rule for it and close the issue.
