### ISSUE TITLE
Addition for Mac users in index_2.md for generating GitHub token as environment variable

### ISSUE THREAD

**Issue by marabuuu** [NFDI4BIOIMAGE/training#172]
Hi @SeverusYixin,

Thank you for your [explanation about how to create a GitHub token](https://github.com/NFDI4BIOIMAGE/training/blob/019ec5e1e50b36c550d11b15285cd080139ce2f9/docs/contributing/index_2.md#prerequisites).  I realised that this line:

`setx GITHUB_API_KEY "your_github_api_key"`

did not work on my Macbook, I tried this instead:
`export GITHUB_API_KEY="your_github_api_key"`
and it worked for me.

Just in case this should be executable for all operating systems.
But very well explained, thanks for the guide!

Best,
Mara

**Comment by SeverusYixin** [comment]
Thank you, the original code was for Windows, and I'm going to add as you suggest :)

Best,
Yixin

**Comment by SeverusYixin** [comment]
This has also been completed and could be closed. @haesleinhuepf
