### ISSUE TITLE
Repetition of the data source Problem

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/training#209]
Hi @haesleinhuepf, it was interesting that I just found in our database, we have two data sources which names are the same: "FAIR data handling for microscopy: Structured metadata annotation in OMERO":

https://github.com/NFDI4BIOIMAGE/training/blob/e9aeac1a7738c2b7497406af00b0923f4b7f5065/resources/nfdi4bioimage.yml#L312

https://github.com/NFDI4BIOIMAGE/training/blob/e9aeac1a7738c2b7497406af00b0923f4b7f5065/resources/nfdi4bioimage.yml#L2580

would you mind help me also check it, their url is the same but the description is a little different

**Comment by haesleinhuepf** [comment]
Can your remove both from the database and submit a new Github issue with the zenodo link as descritiption only? Our github action will then automatically find the correct meta-data and send a pull-request. Thanks!
