### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#284]
Reported by @SeverusYixin 

E.g. [here](https://github.com/NFDI4BIOIMAGE/training/actions/runs/11345886942/job/31553751356?pr=274) the error is:
```
Run actions/setup-python@v1
Error: Version 3.7 with arch x64 not found
```

Hence, we need to update our github workflows. E.g. upgrade the Python version here: https://github.com/NFDI4BIOIMAGE/training/blob/main/.github/workflows/book.yml#L18-L21
and here:
https://github.com/NFDI4BIOIMAGE/training/blob/main/.github/workflows/test.yml#L17-L20

@SeverusYixin would you mind giving this a try and see if this solves the problem? Thanks!

**Comment by SeverusYixin** [comment]
I will do it after debugging my script :)
