### ISSUE TITLE
Highlights of Download stats on main page.

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#285]
It would be great if we had a script that determines the recently most downloaded zenodo records, similar to [this notebook](https://github.com/NFDI4BIOIMAGE/training/blob/main/notebooks/download_stats.ipynb): and then updates the website [main page](https://github.com/NFDI4BIOIMAGE/training/blob/main/docs/readme.md). For example, it could replace a placeholder such as `{most_downloaded}` with some actual content.

Optional: It could download the most downloaded thing, turn it into a PNG and show it on the main page. This will not work with all contents obviously, but with PPTx or PDFs.

git-bob comment: Given a zenodo record url, how would you automatically download the first file from this zenodo record using the zenodo API and if its a PPT or PDF turn the first slide or page into a PNG?

**Comment by haesleinhuepf** [comment]
Hi @marabuuu ,

as discussed yesterday, could you please check if this works or can be made to work? (-:

Thanks!

Best,
Robert

**Comment by marabuuu** [comment]
Yes, I am happy to look into this :)
