### ISSUE TITLE
Update the publication_date: git-bob

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/training#289]
In the folder "resource" there is a yml-file named "nfdi4bioimage.yml". There is a lot of data like "- authors:

Elisabeth Kugler
title: 'Sharing Your Poster on Figshare: A Community Guide to the How-To and Why
Tags:
Sharing
Research Data Management
type:
Blog
url: https://focalplane.biologists.com/2023/07/26/sharing-your-poster-on-figshare/", obviously not all of them have publication_date. It would be great if we had a script based on the "url" of each data in "nfdi4bioimage.yml", try to find the publication date and update in this yml file.

git-bob comment

**Comment by haesleinhuepf** [comment]
git-bob fails with this issue because the yml file is too big ([details](https://github.com/NFDI4BIOIMAGE/training/actions/runs/11367913973/job/31621737581)), error: 
```
openai.APIStatusError: Error code: 413 - {'error': {'code': 'tokens_limit_reached', 'message': 'Request body too large for gpt-4o model. Max size: 8000 tokens.', 'details': None}}
```

**Comment by SeverusYixin** [comment]
Haha, an interesting git-bob, I'm also very glad to join you to have more information about it, it looks like our "Jarvis"
