### ISSUE TITLE
 python version setting: @V2 to @ V4 

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/training#291]
Hi @haesleinhuepf,

seems to be the python version setting (@v2) in https://github.com/NFDI4BIOIMAGE/training/blob/2f3578e05b40c6a6aaf942003118a43bc12eaf1a/.github/workflows/auto-add-download-statistics.yml#L15

and here 
https://github.com/NFDI4BIOIMAGE/training/blob/2f3578e05b40c6a6aaf942003118a43bc12eaf1a/.github/workflows/auto-add-zenodo-entries.yml#L21

and here 
https://github.com/NFDI4BIOIMAGE/training/blob/2f3578e05b40c6a6aaf942003118a43bc12eaf1a/.github/workflows/git-bob.yml#L36

all of these are "actions/setup-python@v2", should i update all of them to "actions/setup-python@v4"?

Because currently  the git run as 
0s
Run actions/setup-python@v2
Successfully setup CPython (3.[1](https://github.com/NFDI4BIOIMAGE/training/actions/runs/11380795947/job/31660824080?pr=290#step:5:1)2.7)

Best,
Yixin

**Comment by SeverusYixin** [comment]
It doesn't seem very smart, or am I using it the wrong way? But still interesting XD

**Comment by haesleinhuepf** [comment]
These answers seem reasonable to me @SeverusYixin . I should maybe update git-bob to not answer stuff that has been answered before already.

**Comment by SeverusYixin** [comment]
> These answers seem reasonable to me @SeverusYixin . I should maybe update git-bob to not answer stuff that has been answered before already.

So, should I update the relevant code ?

**Comment by haesleinhuepf** [comment]
It was already done. Let's test see if it works:

git-bob comment on:
* We have a couple of python files in the scripts folder. What are they doing?
* What would be a good strategy to reorganize this code?

**Comment by SeverusYixin** [comment]
hmm, but it was still "uses: actions/setup-python@v2" in the script

**Comment by SeverusYixin** [comment]
in the code of 

[training/.github/workflows/auto-add-download-statistics.yml](https://github.com/NFDI4BIOIMAGE/training/blob/2f3578e05b40c6a6aaf942003118a43bc12eaf1a/.github/workflows/auto-add-download-statistics.yml#L15)

Line 15 in [2f3578e](https://github.com/NFDI4BIOIMAGE/training/commit/2f3578e05b40c6a6aaf942003118a43bc12eaf1a)

 - name: Set up Python 
and here

[training/.github/workflows/auto-add-zenodo-entries.yml](https://github.com/NFDI4BIOIMAGE/training/blob/2f3578e05b40c6a6aaf942003118a43bc12eaf1a/.github/workflows/auto-add-zenodo-entries.yml#L21)

Line 21 in [2f3578e](https://github.com/NFDI4BIOIMAGE/training/commit/2f3578e05b40c6a6aaf942003118a43bc12eaf1a)

 uses: actions/setup-python@v2 
and here

[training/.github/workflows/git-bob.yml](https://github.com/NFDI4BIOIMAGE/training/blob/2f3578e05b40c6a6aaf942003118a43bc12eaf1a/.github/workflows/git-bob.yml#L36)

Line 36 in [2f3578e](https://github.com/NFDI4BIOIMAGE/training/commit/2f3578e05b40c6a6aaf942003118a43bc12eaf1a)

 uses: actions/setup-python@v2 
all of these are "actions/setup-python@v2". They all still use "actions/setup-python@v2", update them to "uses: actions/setup-python@v4" with code comments.

git-bob implement this!

**Comment by haesleinhuepf** [comment]
As git-bob is a github workflow, it is not allowed to modify github-workflows

**Comment by SeverusYixin** [comment]
> As git-bob is a github workflow, it is not allowed to modify github-workflows

Hmmm, question, perhaps a little rude, are you git-bob or Robert XD, how can you answer so quickly when everytime I try git-bob. XDD

**Comment by haesleinhuepf** [comment]
Also, again, your task description is not easy to read @SeverusYixin . Try to use clear english sentences. "In file xyz.py, update V2 to V4" and git-bob will be able help you.

**Comment by SeverusYixin** [comment]
Ahhh, I got it, I will try it next time haha
