### ISSUE TITLE
Some things that could be improved for the Submission App

### ISSUE THREAD

**Issue by lea-33** [NFDI4BIOIMAGE/training#297]
Now that the App actually works for me, I found some things while testing it that could be approved (in my opinion):

- [x] License Option "cc-by-sa-nc" is missing
- [x] no instructions for Linux regarding the installation process of the App (https://nfdi4bioimage.github.io/training/contributing/submit_app.html)
- [x] some tags are doubled in different forms (e.g. Bioimage Analysis and Bio-Image Analysis). I think it is somehow confusing and I would sugggest to edit the yml file such that only one option is there. I'm not sure if it has to be changed manually in the appsubmission.py or if the App only displays options from the yml file. 
I would suggest using only: 
- Bioimage Analysis (instead of mixing it with Bio-Image Analysis)
- OMERO (instead of mixing it with Omero)
- cc-by-... (instead of mixing it with CC-BY... - just because it is used with lowercase most of the time)

**Comment by haesleinhuepf** [comment]
Hey @lea-33 ,

as just discussed, there is a data-clean-up script [here](https://github.com/NFDI4BIOIMAGE/training/blob/main/scripts/data_normalizer.py) which might profit from additional routines for doing exactly what you are proposing here. 

@SeverusYixin : Do you know if the data-normlizer already does some of the things above?

Thanks!

**Comment by SeverusYixin** [comment]
These require additional adjustments: ‘Bioimage Analysis and Bio-Image Analysis’, ‘OMERO (instead of mixing it with Omero)
’, “cc-by-”, due to the problems with the original data source, we can choose to create additional rules for them in the code, or modify them manually.

So which one did you prefer?

**Comment by lea-33** [comment]
> Hey @lea-33 , Thank you for the detailed information. I will update the data normalisation process later.
> 
> @haesleinhuepf, In my memory, the "cc-by-sa-nc" is a specific version, we have changed it to others.

I think it should not be a problem anymore as the Options in the App are created from the different options that already exists in the yml file. The last pull request I did when trying the App (that one that actually worked) included a cc-by-sa-nc license so from now on it SHOULD be part of the options in the app because it is part of the yml file (after the pull request is accepted and the yml file is updated /merged).

**Comment by haesleinhuepf** [comment]
It might be key to curate the data in the yml file at a different time-point in our workflow: e.g. when a pull-request is submitted (before a new entry goes into the database), and not when the website is built.

**Comment by SeverusYixin** [comment]
> > These require additional adjustments: ‘Bioimage Analysis and Bio-Image Analysis’, ‘OMERO (instead of mixing it with Omero) ’, “cc-by-”, due to the problems with the original data source, we can choose to create additional rules for them in the code, or modify them manually.
> > So which one did you prefer?
> 
> I would prefer each first option. I already changed it in the new YML file for now (I have not sent a pull request yet because I am still adding some new entries, but I will send it next week!). So after that there shouldn't be the second 'unwanted' option displayed in the App anymore (unless someone manually adds them again, which I don't think will happen).

Nice, my current website setting was based on the github resource but not the local datasource anymore. This means that it will have the latest data in real time. It is worth discussing how often we let the web page update the database. Currently it is every time docker compose up --build.
