### ISSUE TITLE
Add comment paper "Multimodal large language models for bioimage analysis"

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#301]
https://www.nature.com/articles/s41592-024-02334-2

CC @rmassei ;-)

**Comment by haesleinhuepf** [comment]
Also here under CC-BY-NC-SA license: https://arxiv.org/abs/2407.19778

**Comment by rmassei** [comment]
https://github.com/NFDI4BIOIMAGE/training/pull/308
