### ISSUE TITLE
Add  Lazy Parallel Processing and Visualization of Large Data with ImgLib2, BigDataViewer, the N5-API, and Spark

### ISSUE THREAD

**Issue by ClementCaporal** [NFDI4BIOIMAGE/training#319]
https://saalfeldlab.github.io/i2k2024-lazy-workshop/ 

I2K workshop, one at a time!

**Comment by lea-33** [comment]
added the material in this new (branch)[https://github.com/NFDI4BIOIMAGE/training/tree/317-add-i2k-qupath-for-python-programmers] from another Issue #317.
