### ISSUE TITLE
Add I2K 2024: clEsperanto: GPU-Accelerated Image Processing Library

### ISSUE THREAD

**Issue by ClementCaporal** [NFDI4BIOIMAGE/training#325]
https://github.com/StRigaud/clesperanto_workshop_I2K24?tab=readme-ov-file

**Comment by lea-33** [comment]
added the material in this new [branch](https://github.com/NFDI4BIOIMAGE/training/tree/317-add-i2k-qupath-for-python-programmers) from another Issue #317.
