### ISSUE TITLE
Publication date Normalized

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/training#340]
Our data source includes the following information as:
https://github.com/NFDI4BIOIMAGE/training/blob/3d5346f828c289342b57f0b68914bea930185035/resources/nfdi4bioimage.yml#L1165

https://github.com/NFDI4BIOIMAGE/training/blob/3d5346f828c289342b57f0b68914bea930185035/resources/nfdi4bioimage.yml#L1181

https://github.com/NFDI4BIOIMAGE/training/blob/3d5346f828c289342b57f0b68914bea930185035/resources/nfdi4bioimage.yml#L2993

https://github.com/NFDI4BIOIMAGE/training/blob/3d5346f828c289342b57f0b68914bea930185035/resources/nfdi4bioimage.yml#L3048

https://github.com/NFDI4BIOIMAGE/training/blob/3d5346f828c289342b57f0b68914bea930185035/resources/nfdi4bioimage.yml#L3101

https://github.com/NFDI4BIOIMAGE/training/blob/3d5346f828c289342b57f0b68914bea930185035/resources/nfdi4bioimage.yml#L3708

https://github.com/NFDI4BIOIMAGE/training/blob/3d5346f828c289342b57f0b68914bea930185035/resources/nfdi4bioimage.yml#L3737

https://github.com/NFDI4BIOIMAGE/training/blob/3d5346f828c289342b57f0b68914bea930185035/resources/nfdi4bioimage.yml#L3756

https://github.com/NFDI4BIOIMAGE/training/blob/3d5346f828c289342b57f0b68914bea930185035/resources/nfdi4bioimage.yml#L3771

We should normalize them as YYYY-MM-DD 

It seems that Webcrawler is not allowed, so we have to change it manually, right?

**Comment by lea-33** [comment]
Maybe we could just list them as YYYY-01-01 then? If those are only those few entries I could change them manually.

**Comment by haesleinhuepf** [comment]
> We should normalize them as YYYY-MM-DD

May I ask why this is necessary?

**Comment by SeverusYixin** [comment]
> > We should normalize them as YYYY-MM-DD
> 
> May I ask why this is necessary?

In our new filter card, we will have filters for both publication_date and submit_date. To ensure consistency, we should normalize these dates so they all follow the format YYYY-MM-DD, rather than having a mix of YYYY and YYYY-MM-DD. However, if you’re okay with the variation, normalization isn’t necessary.

**Comment by SeverusYixin** [comment]
> Maybe we could just list them as YYYY-01-01 then? If those are the only entries to change I could/would do it manually.

Seems on the original link(url) has the exactly date, but I'm not sure do we need to do that.

**Comment by SeverusYixin** [comment]
Maybe this makes it clearer?

> > We should normalize them as YYYY-MM-DD
> 
> May I ask why this is necessary?

![3](https://github.com/user-attachments/assets/b77ceea7-afb5-45b5-9cf1-c826a6d8365e)
