### ISSUE TITLE
add materials

### ISSUE THREAD

**Issue by cwetzker** [NFDI4BIOIMAGE/training#341]
https://zenodo.org/records/14014252
https://zenodo.org/records/14001388
https://zenodo.org/records/13991322
https://zenodo.org/records/13831274

**Comment by haesleinhuepf** [comment]
git-bob split this into 4 issues

**Comment by haesleinhuepf** [comment]
Awesome, thanks Conni @cwetzker ! The entries have been added to the database :-)
