### ISSUE TITLE
Any way to point to updated resource?

### ISSUE THREAD

**Issue by petebankhead** [NFDI4BIOIMAGE/training#42]
This is a great collection :)

My 'Analyzing fluorescence microscopy images with ImageJ' is [here](https://github.com/NFDI4BIOIMAGE/training/blob/024bac698c4e4c1dc11a6782d31de3bde685e512/resources/materials.yml#L542) with an unknown license.

That's correct, and is the reason why I recreated it as 'Introduction to bioimage analysis' (CC-BY) [here](https://github.com/NFDI4BIOIMAGE/training/blob/024bac698c4e4c1dc11a6782d31de3bde685e512/resources/materials.yml#L29).

Is there any way to link the first, so that it points to the second? Or just remove 'Analyzing fluorescence microscopy images with ImageJ'?

GitBook has changed how they operate entirely, so I'm struggling to access it myself and unable to make changes - so will likely just take it offline at some point (if I can figure out how...).

**Comment by haesleinhuepf** [comment]
> Or just remove 'Analyzing fluorescence microscopy images with ImageJ'?

That's no problem! I'll just do it. 

Mid-/long-term we need to define a blacklist for stuff we don't want to be listed though...
