### ISSUE TITLE
Enhance data_normalizer to Handle Unknown Author Data Formats

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/training#517]
The upgrade is necessary to handle diverse and unknown author data formats as the project evolves. Using **pandas**, **spacy**, and **nameparser_HumanName** will enhance the data_normalizer for better accuracy, scalability, and reliability. Let's try it.

**Comment by haesleinhuepf** [comment]
Can you please provide a link to nameparser_HumanName?

**Comment by SeverusYixin** [comment]
> Can you please provide a link to nameparser_HumanName?
> 
> Edit: and also to spacey please. Also why do you think these libraries are the way t

**Comment by SeverusYixin** [comment]
> Can you please provide a link to nameparser_HumanName?
> 
> Edit: and also to spacey please. Also why do you think these libraries are the way to go?

The nameparser library, with its extensive database of names, is well-suited for recognizing complex names. For example, you can find more details in the following resources:
https://predictivehacks.com/name-parser-with-python
https://nameparser.readthedocs.io/en/latest/modules.html
On the other hand, spaCy, as an advanced natural language processing (NLP) library, also offers capabilities for detecting names. You can learn more about spaCy's features here:
https://explosion.ai/about
Currently, I'm not entirely sure whether spaCy will be helpful for name detection, as I've encountered some unexpected results when using nameparser alone. I am still in the process of testing and comparing these tools.

**Comment by SeverusYixin** [comment]
Of course, if you have any ideas that you can add them here, because every time when It met the author like "Fuchs, Vanessa Aphaia Fiona" can not be recognize correctly. I'm just try to test it.

**Comment by SeverusYixin** [comment]
> Of course, if you have any ideas that you can add them here, because every time when It met the author like "Fuchs, Vanessa Aphaia Fiona" can not be recognize correctly. I'm just try to test it.

And in our currently Data_normalizer version of PR #516, it has only one problem is the Fuchs, Vanessa Aphaia Fiona will be seperated in Fuchs and Vanessa Aphaia Fiona, so if you think that we don't need this update, then we can cancle it.

**Comment by haesleinhuepf** [comment]
It looks like a lot of work. I'm not sure if it is necessary. How many cases are there currently approximately where author names are wrong in the yaml file?

**Comment by SeverusYixin** [comment]
> It looks like a lot of work. I'm not sure if it is necessary. How many cases are there currently approximately where author names are wrong in the yaml file?

Currently, I only find one type is "Fuchs, Vanessa Aphaia Fiona", which means "name, a long first name"

**Comment by haesleinhuepf** [comment]
Then I propose to fix this issue manually and not introduce new python libraries for this.
