### ISSUE TITLE
Enhance Readability of YAML File Output for Improved Maintenance

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/training#534]
As the content in the YAML file continues to grow, improving its readability would significantly benefit maintenance efforts. Currently, the script's output is functional and displays correctly on the website, but the format in the YAML file after be normalized should make it easier to read and manage.

Proposal:
Modify the script's output to improve the formatting and readability of the generated YAML file. 

1. Ensure that the YAML file remains clear and maintainable as the data grows.
2. Keep the output consistent with the standards for better collaboration and future updates.

This issue related to https://github.com/NFDI4BIOIMAGE/training/pull/533#discussion_r1862567103

**Comment by haesleinhuepf** [comment]
Let me just add some substance to this issue: I presume this script: scripts/data_normalizer.py makes umlauts less readable when modifying our yml file. For example it turns `Maximilian Müller` into `Maximilian M\xFCller`.

git-bob think about how this could be resolved.
