### ISSUE TITLE
Matherial from the “Euro-BioImaging’s  Guide to FAIR BioImage Data"

### ISSUE THREAD

**Issue by rmassei** [NFDI4BIOIMAGE/training#90]
We should add the public material from this course:
Euro-BioImaging Youtube channel (https://www.youtube.com/c/eurobioimagingcommunication)

Practical Exercise
https://zenodo.org/records/11474407

**Most important document (maybe to add even in a separe entry):**
data management plan template (https://zenodo.org/records/11473803

**Comment by haesleinhuepf** [comment]
Hi @rmassei ,

the first link points to a YouTube channel (which is already in our collection).

Could you provide a link to the specific course video you mean?

**Comment by rmassei** [comment]
ah sorry @haesleinhuepf! here we are:

FAIR BioImage Data 

https://www.youtube.com/watch?v=8zd4KTy-oYI&list=PLW-oxncaXRqU4XqduJzwFHvWLF06PvdVm

**Comment by haesleinhuepf** [comment]
done in #92
