### ISSUE TITLE
App for adding entries

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#94]
It should be pretty straightforward to program a [web]app that contains a form (urls, author, description, licence etc) and once the user clicks "Submit", a github issue or even a git pull-request is submitted. 

Ideally, one does not need to login. This might be achievable by creating an github API key, that can only create issues or send PRs to one specific repository.

**Comment by haesleinhuepf** [comment]
Helpful links: 
[streamlit apps](https://streamlit.io/)
[Github REST API endpoint for creating issues](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue)

**Comment by haesleinhuepf** [comment]
Hi @SeverusYixin ,

I'm just formalting the goal of this task more clearly: We need a digital form of these parameters:
```
Name*:
Description:
Author(s):
License:
Url(s)*:
Tags:

* mandatory
```

When submitting the form, technically the process described here should be done automatically: https://nfdi4bioimage.github.io/training/contributing/index.html#step-by-step-tutorial

Let me know if you have open questions!

**Comment by SeverusYixin** [comment]
Ok, I got it

**Comment by haesleinhuepf** [comment]
Please do not close issues until your changes have been merged in the main branch.
