### ISSUE TITLE
Data cleaning

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#99]
I recently saw that our data needs a little cleaning. For example, same licenses are called differently here:
- https://github.com/NFDI4BIOIMAGE/training/blob/edf1e0ded6b77ab4ff8ed04c074cf955e638419a/resources/materials.yml#L16
- https://github.com/NFDI4BIOIMAGE/training/blob/edf1e0ded6b77ab4ff8ed04c074cf955e638419a/resources/materials.yml#L51
- https://github.com/NFDI4BIOIMAGE/training/blob/edf1e0ded6b77ab4ff8ed04c074cf955e638419a/resources/materials.yml#L1515

We should also check other entries such as tags if there might be similar issues.

It would be great if we could standardize these meta data entries, of course ideally automatically. The notebook here might help as it summarizes existing licenses:

https://github.com/NFDI4BIOIMAGE/training/blob/main/scripts/license_statistics.ipynb

@SeverusYixin would you mind having looking into this? Thank you!

**Comment by haesleinhuepf** [comment]
> hmmm, I didn't get the requirement point here.
> 
> E.g. this is the first one, am I right ? authors: Robert Haase et al. license:
> 
> * CC BY 4.0
> * BSD 3-clause
>   name: BioImage Analysis Notebooks
>   tags:
> * python
> * bioimage analysis
>   type:
> * book
> * notebook
>   url: https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/intro.html
> 
> and second is this:
> 
> * license: cc-by-4.0
>   name: OME Documentation
>   tags:
>   
>   * omero
>     type:
>   * documentation
>     url: https://www.openmicroscopy.org/docs/
> 
> 3rd:
> 
> * authors: Isabel Kemmer
>   license:  Creative Commons Attribution 4.0 International
>   name: Euro-BioImaging Guide to FAIR BioImage Data - Practical Tasks
>   description: "Hands-on exercises on FAIR Bioimage Data from the interactive online workshop Euro-BioImaging Guide to FAIR BioImage Data 2024"
>   tags:
>   
>   * bioimage analysis
>   * FAIR-principles
>   * research data management
>     type:
>   * slides
>   * tutorial
>     url: https://zenodo.org/records/11474407
> 
> these three all belong to the same license, so your requirement is that we want to use the same license for them like all of them should be used as cc-by-4.0? Am I right? So what's the "primary key" of them, I mean how can I make sure that like Creative Commons Attribution 4.0 International or CC BY 4.0 or some others are same? Base on "https://github.com/NFDI4BIOIMAGE/training/blob/main/scripts/license_statistics.ipynb" to check it ? So it need something like an app can automatically correct them with same license, am I right ?

Yes, exactly! I also don't know yet, how to ensure these are the same licenses, but I presume it is possible to program this. First, we need to find out what would be a good identifier for the license. Maybe, the SPOX license ID is a starting point? https://spdx.org/licenses/ or https://opensource.org/license . Please explore a bit what kind of standards exist.



> So it need something like an app can automatically correct them with same license, am I right ?

Yes, that would be cool. We could build this into the github workflow for example like we do [here](https://github.com/NFDI4BIOIMAGE/training/blob/edf1e0ded6b77ab4ff8ed04c074cf955e638419a/.github/workflows/book.yml#L31) and [here](https://github.com/NFDI4BIOIMAGE/training/blob/edf1e0ded6b77ab4ff8ed04c074cf955e638419a/scripts/generate_link_lists.py#L66), to check for duplicate entries in our database. Or this could be a standalone app / notebook we call from time to time to check for consistency of our data.

**Comment by SeverusYixin** [comment]
You can check if that's what you need

**Comment by haesleinhuepf** [comment]
As just discussed, it would be great if the license normalization script would run as part of the github workflow:
* [when sending a PR](https://github.com/NFDI4BIOIMAGE/training/blob/597140be28888960b3373f1ef3d6339d57dfc2a1/.github/workflows/test.yml#L30)
* [when updating the website](https://github.com/NFDI4BIOIMAGE/training/blob/597140be28888960b3373f1ef3d6339d57dfc2a1/.github/workflows/book.yml#L31)

**Comment by haesleinhuepf** [comment]
It would also be cool to have a list of questionable licenses, e.g. as notebook as in #101

**Comment by SeverusYixin** [comment]
As just discussed, all authors, types, tags should be a list when normalised, what about licences? Should licences also be a list? It seems that only in materials.yml, the licence on line 15 is a list.

**Comment by haesleinhuepf** [comment]
> Should licences also be a list? It seems that only in materials.yml, the licence on line 15 is a list.

If you are referring to [this place](https://github.com/NFDI4BIOIMAGE/training/blob/main/resources/materials.yml#L15-L17), yes, these should be a list. Everything that are multiple entities should be lists. Otherwise, if we start with `a, b, c`  or `a and b and c` or `a; b; c` we go crazy. Let's use the [YML standard for lists](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html) if possible.

**Comment by haesleinhuepf** [comment]
Please do not close issues until your changes have been merged in the main branch.
